server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-user
          uri: lb://ms-user
          predicates:
            - Path=/user/**

        - id: ms-credit
          uri: lb://ms-credit
          predicates:
            - Path=/credit/**

        - id: ms-checkrules
          uri: lb://ms-checkrules
          predicates:
            - Path=/checkrules/**

        - id: ms-document
          uri: lb://ms-document
          predicates:
            - Path=/file/**
