server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-user-service
          uri: lb://ms-user-service
          predicates:
            - Path=/user/**

        - id: ms-request-service
          uri: lb://ms-request-service
          predicates:
            - Path=/request/**

        - id: ms-simulate-service
          uri: lb://ms-simulate-service
          predicates:
            - Path=/simulate

        - id: ms-evaluation-service
          uri: lb://ms-evaluation-service
          predicates:
            - Path=/checkrules/**

        - id: ms-track-service
          uri: lb://ms-track-service
          predicates:
            - Path=/track/**