apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user-deployment
  labels:
    app: ms-user-deployment
spec:
  selector:
    matchLabels:
      app: ms-user-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-user-deployment
    spec:
      containers:
        - name: ms-user
          image: thxmohamed/user-service
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0" 
            - name: DB_HOST
              value: "user-db-service"  
            - name: DB_PORT
              value: "3306" 
            - name: DB_NAME
              value: "user" 
            - name: DB_USER
              value: "root"  
            - name: DB_PASSWORD
              value: "mohamed123" 